noinst_HEADERS +=                                                              \
    %reldir%/prefix_outage_event.hpp                                           \
    %reldir%/as_outage_event.hpp                                               \
    ${NOTHING}
