#ifndef BGP_PLATFORM_UTILS_DEFS_HPP_
#define BGP_PLATFORM_UTILS_DEFS_HPP_

#define BGP_PLATFORM_NAMESPACE       bgp_platform
#define BGP_PLATFORM_NAMESPACE_BEGIN namespace BGP_PLATFORM_NAMESPACE {
#define BGP_PLATFORM_NAMESPACE_END   }

#endif  // BGP_PLATFORM_UTILS_DEFS_HPP_
